server:
  port: 80
  connection-timeout: 1800000

spring:
  datasource:
    url: jdbc:postgresql://ec2-46-137-113-157.eu-west-1.compute.amazonaws.com:5432/dffu5h5gn964at
    username: zuahkgtwrcflpu
    password: 8f94970d288b26bb72a48a9eaeafe82f03eb76baed10dc10b149b15777d87e92
    name: zuahkgtwrcflpu
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/aviatickets
#    username: postgres
#    password: 123456
#    name: aviatickets
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect